apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template: # this will apply a label (an identifier to the pod that is going to be created)
    metadata:
      labels:
        app: todo # this is the label
    spec:
      containers:
        - name: todo
          image: todo_image:0.0.1